# Generated by Django 5.2.15 on 2026-07-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertruletask',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='asyncalertruletask',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='alertruletask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='asyncalertruletask',
            name='status',
        ),
        migrations.AddField(
            model_name='alertruletask',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asyncalertruletask',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
