# Generated by Django 5.2.15 on 2026-06-09 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('example', '0002_asyncalerttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertruletask',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='asyncalertruletask',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='django_celery_beat.periodictask'),
        ),
    ]
